bootstrap.yml
name: Bootstrap repo
on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Generate skeleton
        shell: bash
        run: |
          cat > create_repo.sh <<'SCRIPT'
          #!/usr/bin/env bash
          set -euo pipefail

          SOLUTION_NAME="GolfTracker"
          API_PORT=5000
          DB_USER="golf"
          DB_PASS="golfpass"
          DB_NAME="golftracker"
          DB_PORT=5432

          echo "Creating repo skeleton..."

          mkdir -p server web

          cat > .gitignore <<'EOF'
          **/bin/
          **/obj/
          *.user
          *.suo
          node_modules/
          dist/
          .vite/
          .env
          .DS_Store
          *.log
          EOF

          cat > docker-compose.yml <<EOF
          version: "3.8"
          services:
            db:
              image: postgres:16
              environment:
                POSTGRES_USER: ${DB_USER}
                POSTGRES_PASSWORD: ${DB_PASS}
                POSTGRES_DB: ${DB_NAME}
              ports:
                - "${DB_PORT}:5432"
              volumes:
                - pgdata:/var/lib/postgresql/data
          volumes:
            pgdata:
          EOF

          cat > README.md <<'EOF'
          GolfTracker monorepo (ASP.NET Core 8 + EF Core Postgres + SignalR + React + MapLibre + Mapillary)
